### ISSUE TITLE
Date not working? 

### ISSUE THREAD

**Issue by haleyngonadi** [philippe2803/twitter-analytics-wrapper#1]
Hi. Thank you so much for sharing this, it is exactly what I was looking for. I'm having an issue with getting the a dated version working. When I put in the date, I get this error: 

```
Traceback (most recent call last):
  File "test.py", line 17, in <module>
    reports_filepath = reports.run()            # list of filepaths of downloaded csv reports
  File "/usr/local/lib/python2.7/dist-packages/twitter_analytics/downloader.py", line 81, in run
    ranges = self.split_date_range_into_91()
  File "/usr/local/lib/python2.7/dist-packages/twitter_analytics/downloader.py", line 188, in split_date_range_into_91
    for batch in range(0, number_of_batch):
TypeError: range() integer end argument expected, got float.

```

Here's the exact code I'm using that throws the error:

```
from twitter_analytics import ReportDownloader
import csv
import time
from datetime import date, timedelta


yesterday = date.today() - timedelta(1)
today = time.strftime("%m/%d/%Y")

reports = ReportDownloader(
    username='',
    password='',
    from_date= yesterday.strftime("%m/%d/%Y"),
    to_date=today
)

reports_filepath = reports.run()            # list of filepaths of downloaded csv reports

# Then you can parse the csv simply as follow
tweets = list()
for report in reports_filepath:
    with open(report, 'r') as csvfile:
        r = csv.DictReader(csvfile)
            rows = [row for row in r]
        tweets += rows
```

**Comment by philippe2803** [comment]
Glad you like the library.

Not too sure how and why you used the 'time' lib. Datetime is more than enough in this case. Can you try the following for 'today' instead?

```python
yesterday = date.today() - timedelta(1)
today = date.today()

reports = ReportDownloader(
    username='',
    password='',
    from_date= yesterday.strftime("%m/%d/%Y"),
    to_date=today.strftime("%m/%d/%Y")
)

````
The way the library handles the reports downloaded is not optimum at the moment. Does not prevent from returning the filepaths of reports downloaded before in another process. Happy to hear sugestions.

**Comment by haleyngonadi** [comment]
Hey, thank you for replying. I forgot to tell you I did it the other way and nothing changed as well. I just tried the code you gave and it says the same thing :) 

It retains the filepath even with a different login, you think?

**Comment by philippe2803** [comment]
I think I found something.
Which version of Python are you using? I'm assuming version 2.7. 

It seems the problem is coming from math.ceil method that litterally has a different result between Python 2 and Python 3.

If you use Python 3.5, you will not encounter the problem. I will try to add support for 2.7 at some point. I'm about to put some integration testing, so I'll understand better soon which Python versions will work.

**Comment by haleyngonadi** [comment]
Ah. You were absolutely right. I just used python3 instead and it worked great. Thank you so much. If I come with any ideas re: changing the file path, I'd let you know x)
