### ISSUE TITLE
Create a new pip version

### ISSUE THREAD

**Issue by slipo** [philippe2803/twitter-analytics-wrapper#11]
The version installed by pip doesn't seem to work on Mac. The code in master checking for the correct location of chromedriver on Mac doesn't seem to be there.

**Comment by philippe2803** [comment]
I will update the pip version at some point. Just do not have the time at the moment.
In the meantime you can pip install the repo 

```
pip install https://github.com/user/repository/archive/branch.zip

```

**Comment by philippe2803** [comment]
Leaving this issue open until I will upload to PIP.
