### ISSUE TITLE
The letter "e" seems to delete the previous character when inserting via send_keys()

### ISSUE THREAD

**Issue by Sm4o** [philippe2803/twitter-analytics-wrapper#13]
I've tested with username "test" and the resulting username that gets keyed in Twitter is "est"

I'm using selenium==3.8.1, chrome==64.0 and chromedriver==2.32

**Comment by Sm4o** [comment]
Temporary fix is to use execute_script() function to inject Javascript directly.\

Just to mention I'm using a Mac to access a Linux server through ssh and Xquartz in order to see the graphical output on the chromium browser.

**Comment by philippe2803** [comment]
That should definitely not happened. Have you tried with normal username and password instead and see if you can login?
To see exactly how Chromium behave with the script, you can add show_browser=True as an argument in your ReportsDownloader object.

For instance, taking the example of the Quickstart, it will look like this:

```python
from twitter_analytics import ReportDownloader

reports = ReportDownloader(
    username='<twitter username>',
    password='<twitter password>',
    show_browser=True
)
report_filepath = reports.run()
```

There are some other things you can have control over actually, if look into there: https://github.com/philippe2803/twitter-analytics-wrapper/blob/master/twitter_analytics/downloader.py#L19

For instance, you can use a proxy if needed, or change the folder where reports are downloaded.
