### ISSUE TITLE
Download button has changed I think?

### ISSUE THREAD

**Issue by l0c0luke** [philippe2803/twitter-analytics-wrapper#16]
Getting the below error now. Unfortunately I guess this is a consequence of the game we are trying to play with twitter.

`selenium.common.exceptions.WebDriverException: Message: unknown error: Element <button type="button" class="btn btn-default ladda-button" data-spinner-color="#8899a6" data-style="expand-right" disabled="disabled">...</button> is not clickable at point (969, 91). Other element would receive the click: <div id="export" data-timespan="2678400000" data-export="true">...</div>`

**Comment by rogelj** [comment]
Twitter has done something to it. I am working on a fix. Will do a pull request in due course.

**Comment by philippe2803** [comment]
Thanks for maintaining this. 
I'm unable to do it myself at the moment. I have just accepted your PR.
