### ISSUE TITLE
Chrome_option needs to update to options

### ISSUE THREAD

**Issue by myusercb** [philippe2803/twitter-analytics-wrapper#20]
Hi, 
I have spotted a small error in the code due to chromedriver update. As you can see below the chrome_options has been deprecated and now it is called 'options':

  # Create Chrome Browser
        if SYST == 'darwin':
            self.browser = webdriver.Chrome(r"/usr/local/bin/chromedriver", **chrome_options**=chrome_options)
        elif SYST == 'linux':
            self.browser = webdriver.Chrome(r"/usr/lib/chromium-browser/chromedriver",**options**=chrome_options) #chrome_options needs to change to options

Thank you

**Comment by rogelj** [comment]
This is true is you define this first:

`options = webdriver.ChromeOptions()`

Otherwise the code is fine as it stands.
