### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by mikebawol** [philippe2803/twitter-analytics-wrapper#4]
Any change that this will get some Windows support in the future?

**Comment by philippe2803** [comment]
No plan at the moment, I'm afraid but I accept pull requests though.
Alternatively, you could run an ubuntu docker image on your windows environment, and run your script from there.

**Comment by KobaKhit** [comment]
I made it work on Windows and submitted a pull request #6 

until it is merged @mikebawol you can do `pip install git+https://github.com/KobaKhit/twitter-analytics-wrapper.git` or wait

**Comment by philippe2803** [comment]
Closing as Windows support added.
